service: test-sls # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  #role: arn:aws:iam::12345:role/LambdaRole #For roles based login
  stage: dev
  region: ap-south-1

# you can add packaging information here
#package:
#  include:
#    - include-me.py
#    - include-me-dir/**
#  exclude:
#    - exclude-me.py
#    - exclude-me-dir/**

functions:
##  list:
##    handler: lambda_functions/get_all_responses.list_responses
##    events:
##      - http:
##          path: lambda_functions
##          method: get
##          cors: true
##  delete:
##    handler: lambda_functions/delete_response.delete
##    events:
##      - http:
##          path: lambda_functions/{app_name}
##          method: delete
##          cors: true
##  insert:
##    handler: lambda_functions/insert_response.insert
##    events:
##      - http:
##          path: lambda_functions
##          method: post
##          cors: true
##  evaluate:
##    handler: lambda_functions/evaluate_response.evaluate
##    events:
##      - http:
##          path: lambda_functions/{app_name}
##          method: get
##          cors: true

resources:
  Resources:
      uploadBucket:
          Type: AWS::S3::Bucket
          Properties:
              BucketName: ${self:service}-${self:provider.stage}-uploads
##    TestDynamoDbTable:
##      Type: 'AWS::DynamoDB::Table'
##      DeletionPolicy: Retain
##      Properties:
##        AttributeDefinitions:
##          -
##            AttributeName: app_name
##            AttributeType: S
##        KeySchema:
##          -
##            AttributeName: app_name
##            KeyType: HASH
##        ProvisionedThroughput:
##          ReadCapacityUnits: 1
##          WriteCapacityUnits: 1
##        TableName: ${self:service}-${self:provider.stage}-table1
      
